### ISSUE TITLE
composer panics when curl fails to download a package in the worker

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1378]
```
Apr 23 15:54:05 ip-172-31-67-32.ec2.internal osbuild-worker[14173]: Running 'osbuild' job d0274498-fb07-41a7-96b1-88a643c2187c
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14595]: Traceback (most recent call last):
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14595]:   File "/usr/bin/osbuild", line 33, in <module>
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14595]:     sys.exit(load_entry_point('osbuild==28', 'console_scripts', 'osbuild')())
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14595]:   File "/usr/lib/python3.9/site-packages/osbuild/main_cli.py", line 137, in osbuild_cli
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14595]:     r = manifest.build(
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14595]:   File "/usr/lib/python3.9/site-packages/osbuild/pipeline.py", line 282, in build
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14595]:     source.download(store, libdir)
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14595]:   File "/usr/lib/python3.9/site-packages/osbuild/sources.py", line 55, in download
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14595]:     raise RuntimeError(f"{source}: " + reply["error"])
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14595]: RuntimeError: org.osbuild.curl: curl: error downloading {'url': 'http://ftp.usf.edu/pub/fedora/linux/updates/33/Everything/aarch64/Packages/l/libtirpc-1.2.6-3.rc4.fc33.aarch64.rpm'}: error code 22
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14173]: 2021/04/23 15:54:10 Job d0274498-fb07-41a7-96b1-88a643c2187c failed: error decoding osbuild output: unexpected end of JSON input
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14173]: the raw output:
Apr 23 15:54:10 ip-172-31-67-32.ec2.internal osbuild-worker[14173]: Waiting for a new job...
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]: 2021/04/23 15:54:11 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]: goroutine 325 [running]:
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]: net/http.(*conn).serve.func1(0x400007c500)
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]:         /usr/lib/golang/src/net/http/server.go:1801 +0xf4
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]: panic(0xaaaab6363460, 0xaaaab66bac80)
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]:         /usr/lib/golang/src/runtime/panic.go:975 +0x3f0
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]: github.com/osbuild/osbuild-composer/internal/osbuild1.(*Result).Write(0x0, 0xaaaab64160c0, 0x4000174700, 0xaaaab64160c0, 0x4000174700)
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]:         /builddir/build/BUILD/osbuild-composer-3991bd81f614fd9f03083695958efbada0d2d34b/_build/src/github.com/osbuild/osbuild-composer/internal/osbuild1/result.go:83 +0x28
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]: github.com/osbuild/osbuild-composer/internal/weldr.(*API).composeLogHandler(0x40000eeb80, 0xaaaab641f700, 0x4000174700, 0x40001ccf00, 0x40001c6880, 0x2, 0x4)
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]:         /builddir/build/BUILD/osbuild-composer-3991bd81f614fd9f03083695958efbada0d2d34b/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:2707 +0x394
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]: github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0x40000b0f00, 0xaaaab641f700, 0x4000174700, 0x40001ccf00)
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]:         /usr/share/gocode/src/github.com/julienschmidt/httprouter/router.go:387 +0x9a4
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]: github.com/osbuild/osbuild-composer/internal/weldr.(*API).ServeHTTP(0x40000eeb80, 0xaaaab641f700, 0x4000174700, 0x40001ccf00)
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]:         /builddir/build/BUILD/osbuild-composer-3991bd81f614fd9f03083695958efbada0d2d34b/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:192 +0x114
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]: net/http.serverHandler.ServeHTTP(0x4000174620, 0xaaaab641f700, 0x4000174700, 0x40001ccf00)
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]:         /usr/lib/golang/src/net/http/server.go:2843 +0xbc
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]: net/http.(*conn).serve(0x400007c500, 0xaaaab6421080, 0x400028e580)
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]:         /usr/lib/golang/src/net/http/server.go:1925 +0x6f4
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]: created by net/http.(*Server).Serve
Apr 23 15:54:11 ip-172-31-67-32.ec2.internal osbuild-composer[14172]:         /usr/lib/golang/src/net/http/server.go:2969 +0x2d8
```

seen here: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1207472219

**Comment by teg** [comment]
@gicmo something to improve in osbuild to give structured errors in this case?

**Comment by msehnout** [comment]
See https://github.com/osbuild/osbuild-composer/issues/1414 for more details. @teg do you think this is something to fix in osbuild?

**Comment by gicmo** [comment]
This is totally on the list to fix in osbuild, has been on my mind for a long time. I am laying down the foundations with the new host services infra.

**Comment by msehnout** [comment]
If we expect osbuild to fail with an exception from time to time, should we also fix this on the osbuild-composer side? For example: Is it a good idea to expect JSON output in case osbuild failed?

**Comment by teg** [comment]
I guess we should clarify the different failure modes osbuild can have and handle them appropriately in the worker. Might make sense to discuss this after the host services have landed?
