### ISSUE TITLE
Panic on composeStatus.Result being nil

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#1414]
Journal log:
```
May 18 08:58:24 rhelvm osbuild-composer[13390]: 2021/05/18 08:58:24 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
May 18 08:58:24 rhelvm osbuild-composer[13390]: goroutine 70 [running]:
May 18 08:58:24 rhelvm osbuild-composer[13390]: net/http.(*conn).serve.func1(0xc0000f6140)
May 18 08:58:24 rhelvm osbuild-composer[13390]:         /usr/lib/golang/src/net/http/server.go:1801 +0x147
May 18 08:58:24 rhelvm osbuild-composer[13390]: panic(0x55c24faa55e0, 0x55c24fe14ca0)
May 18 08:58:24 rhelvm osbuild-composer[13390]:         /usr/lib/golang/src/runtime/panic.go:975 +0x47a
May 18 08:58:24 rhelvm osbuild-composer[13390]: github.com/osbuild/osbuild-composer/internal/osbuild1.(*Result).Write(0x0, 0x55c24fb59660, 0xc0000f8450, 0x55c24fb5aca0, 0xc0002081c0)
May 18 08:58:24 rhelvm osbuild-composer[13390]:         /builddir/build/BUILD/osbuild-composer-127d10107184ec3e5fecbe8d557d8d23193362df/_build/src/github.com/osbuild/osbuild-composer/internal/osbuild1/result.go:83 +0x3c
May 18 08:58:24 rhelvm osbuild-composer[13390]: github.com/osbuild/osbuild-composer/internal/weldr.(*API).composeLogsHandler(0xc00012a540, 0x55c24fb64520, 0xc0002081c0, 0xc0000bc200, 0xc000240680, 0x2, 0x4)
May 18 08:58:24 rhelvm osbuild-composer[13390]:         /builddir/build/BUILD/osbuild-composer-127d10107184ec3e5fecbe8d557d8d23193362df/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:2695 +0x965
May 18 08:58:24 rhelvm osbuild-composer[13390]: github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00005f3e0, 0x55c24fb64520, 0xc0002081c0, 0xc0000bc200)
May 18 08:58:24 rhelvm osbuild-composer[13390]:         /usr/share/gocode/src/github.com/julienschmidt/httprouter/router.go:387 +0xc7e
May 18 08:58:24 rhelvm osbuild-composer[13390]: github.com/osbuild/osbuild-composer/internal/weldr.(*API).ServeHTTP(0xc00012a540, 0x55c24fb64520, 0xc0002081c0, 0xc0000bc200)
May 18 08:58:24 rhelvm osbuild-composer[13390]:         /builddir/build/BUILD/osbuild-composer-127d10107184ec3e5fecbe8d557d8d23193362df/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:196 +0x13e
May 18 08:58:24 rhelvm osbuild-composer[13390]: net/http.serverHandler.ServeHTTP(0xc000208460, 0x55c24fb64520, 0xc0002081c0, 0xc0000bc200)
May 18 08:58:24 rhelvm osbuild-composer[13390]:         /usr/lib/golang/src/net/http/server.go:2843 +0xa5
May 18 08:58:24 rhelvm osbuild-composer[13390]: net/http.(*conn).serve(0xc0000f6140, 0x55c24fb65ea0, 0xc000226240)
May 18 08:58:24 rhelvm osbuild-composer[13390]:         /usr/lib/golang/src/net/http/server.go:1925 +0x8ad
May 18 08:58:24 rhelvm osbuild-composer[13390]: created by net/http.(*Server).Serve
May 18 08:58:24 rhelvm osbuild-composer[13390]:         /usr/lib/golang/src/net/http/server.go:2969 +0x36c
```

The JobStatus function from worker/server.go can return OSBuildOutput = nil:
```go
func (s *Server) JobStatus(id uuid.UUID, result interface{}) (*JobStatus, []uuid.UUID, error) {
	rawResult, queued, started, finished, canceled, deps, err := s.jobs.JobStatus(id)
	if err != nil {
		return nil, nil, err
	}

	if !finished.IsZero() && !canceled {
		err = json.Unmarshal(rawResult, result)
		if err != nil {
			return nil, nil, fmt.Errorf("error unmarshaling result for job '%s': %v", id, err)
		}
	}

	// For backwards compatibility: OSBuildJobResult didn't use to have a
	// top-level `Success` flag. Override it here by looking into the job.
	if r, ok := result.(*OSBuildJobResult); ok {
		if !r.Success && r.OSBuildOutput != nil {
			r.Success = r.OSBuildOutput.Success && len(r.TargetErrors) == 0
		}
	}

	return &JobStatus{
		Queued:   queued,
		Started:  started,
		Finished: finished,
		Canceled: canceled,
	}, deps, nil
}
```
which is then used in weldr/api.go:getComposeStatus without checking:
```go
	jobStatus, _, err := api.workers.JobStatus(jobId, &result)
	if err != nil {
		panic(err)
	}

	return &composeStatus{
		State:    composeStateFromJobStatus(jobStatus, &result),
		Queued:   jobStatus.Queued,
		Started:  jobStatus.Started,
		Finished: jobStatus.Finished,
		Result:   result.OSBuildOutput,
	}
```
and later used in callers of getComposeStatus, such as weldr/api.go:composeLogsHandler:
```go
	composeStatus := api.getComposeStatus(compose)
	if composeStatus.State != ComposeFinished && composeStatus.State != ComposeFailed {
		errors := responseError{
			ID:  "BuildInWrongState",
			Msg: fmt.Sprintf("Build %s not in FINISHED or FAILED state.", uuidString),
		}
		statusResponseError(writer, http.StatusBadRequest, errors)
		return
	}

	writer.Header().Set("Content-Disposition", "attachment; filename="+id.String()+"-logs.tar")
	writer.Header().Set("Content-Type", "application/x-tar")

	tw := tar.NewWriter(writer)

	// tar format needs to contain file size before the actual file content, therefore the intermediate buffer
	var fileContents bytes.Buffer
	err = composeStatus.Result.Write(&fileContents)
	common.PanicOnError(err)
```

The same from debugger point of view:
```
> github.com/osbuild/osbuild-composer/internal/worker.(*Server).JobStatus() /usr/src/debug/osbuild-composer-29-1.20210517git127d101.fc33.x86_64/_build/src/github.com/osbuild/osbuild-composer/internal/worker/server.go:116 (PC: 0x55c24f8fac1c)
Warning: debugging optimized function
   111:			if !r.Success && r.OSBuildOutput != nil {
   112:				r.Success = r.OSBuildOutput.Success && len(r.TargetErrors) == 0
   113:			}
   114:		}
   115:	
=> 116:		return &JobStatus{
   117:			Queued:   queued,
   118:			Started:  started,
   119:			Finished: finished,
   120:			Canceled: canceled,
   121:		}, deps, nil
(dlv) p result
interface {}(*github.com/osbuild/osbuild-composer/internal/worker.OSBuildJobResult) *{
	Success: false,
	OSBuildOutput: *github.com/osbuild/osbuild-composer/internal/osbuild1.Result nil,
	TargetResults: []*github.com/osbuild/osbuild-composer/internal/target.TargetResult len: 0, cap: 0, nil,
	TargetErrors: []string len: 0, cap: 0, nil,
	UploadStatus: "failure",}
(dlv) so
> github.com/osbuild/osbuild-composer/internal/weldr.(*API).getComposeStatus() /usr/src/debug/osbuild-composer-29-1.20210517git127d101.fc33.x86_64/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:260 (PC: 0x55c24f949d05)
Warning: debugging optimized function
Values returned:
	~r2: (unreadable empty OP stack)
	~r3: (unreadable empty OP stack)
	~r4: (unreadable empty OP stack)

   255:		}
   256:	
   257:		// All jobs are "osbuild" jobs.
   258:		var result worker.OSBuildJobResult
   259:	
=> 260:		jobStatus, _, err := api.workers.JobStatus(jobId, &result)
   261:		if err != nil {
   262:			panic(err)
   263:		}
   264:	
   265:		return &composeStatus{
(dlv) p result
github.com/osbuild/osbuild-composer/internal/worker.OSBuildJobResult {
	Success: false,
	OSBuildOutput: *github.com/osbuild/osbuild-composer/internal/osbuild1.Result nil,
	TargetResults: []*github.com/osbuild/osbuild-composer/internal/target.TargetResult len: 0, cap: 0, nil,
	TargetErrors: []string len: 0, cap: 0, nil,
	UploadStatus: "failure",}
(dlv) so
> github.com/osbuild/osbuild-composer/internal/weldr.(*API).composeLogsHandler() /usr/src/debug/osbuild-composer-29-1.20210517git127d101.fc33.x86_64/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:2678 (PC: 0x55c24f964819)
Warning: debugging optimized function
Values returned:
	~r1: (unreadable empty OP stack)

  2673:			}
  2674:			statusResponseError(writer, http.StatusBadRequest, errors)
  2675:			return
  2676:		}
  2677:	
=>2678:		composeStatus := api.getComposeStatus(compose)
  2679:		if composeStatus.State != ComposeFinished && composeStatus.State != ComposeFailed {
  2680:			errors := responseError{
  2681:				ID:  "BuildInWrongState",
  2682:				Msg: fmt.Sprintf("Build %s not in FINISHED or FAILED state.", uuidString),
  2683:			}
(dlv) n
> github.com/osbuild/osbuild-composer/internal/weldr.(*API).composeLogsHandler() /usr/src/debug/osbuild-composer-29-1.20210517git127d101.fc33.x86_64/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:2679 (PC: 0x55c24f964829)
Warning: debugging optimized function
  2674:			statusResponseError(writer, http.StatusBadRequest, errors)
  2675:			return
  2676:		}
  2677:	
  2678:		composeStatus := api.getComposeStatus(compose)
=>2679:		if composeStatus.State != ComposeFinished && composeStatus.State != ComposeFailed {
  2680:			errors := responseError{
  2681:				ID:  "BuildInWrongState",
  2682:				Msg: fmt.Sprintf("Build %s not in FINISHED or FAILED state.", uuidString),
  2683:			}
  2684:			statusResponseError(writer, http.StatusBadRequest, errors)
(dlv) p composeStatus
*github.com/osbuild/osbuild-composer/internal/weldr.composeStatus {
	State: ComposeFailed (3),
	Queued: time.Time {
		wall: 606300724,
		ext: 63756923605,
		loc: *time.Location nil,},
	Started: time.Time {
		wall: 614118615,
		ext: 63756923605,
		loc: *time.Location nil,},
	Finished: time.Time {
		wall: 321051230,
		ext: 63756923608,
		loc: *time.Location nil,},
	Result: *github.com/osbuild/osbuild-composer/internal/osbuild1.Result nil,}

... eventually fails here

(dlv) 
> github.com/osbuild/osbuild-composer/internal/weldr.(*API).composeLogsHandler() /usr/src/debug/osbuild-composer-29-1.20210517git127d101.fc33.x86_64/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:2695 (hits goroutine(90):1 total:3) (PC: 0x55c24f964dbb)
Warning: debugging optimized function
  2690:	
  2691:		tw := tar.NewWriter(writer)
  2692:	
  2693:		// tar format needs to contain file size before the actual file content, therefore the intermediate buffer
  2694:		var fileContents bytes.Buffer
=>2695:		err = composeStatus.Result.Write(&fileContents)
  2696:		common.PanicOnError(err)
  2697:	
  2698:		header := &tar.Header{
  2699:			Name:    "logs/osbuild.log",
  2700:			Mode:    0644,
(dlv) 



```

**Comment by msehnout** [comment]
Running the same manifest using plain osbuild:
```
[root@rhelvm delve]# jq .args.manifest /var/lib/osbuild-composer/jobs/3ea271f9-3a66-41df-bc25-946c7c72cdd1.json | osbuild --json --output /tmp -
Traceback (most recent call last):
  File "/usr/bin/osbuild", line 33, in <module>
    sys.exit(load_entry_point('osbuild==28', 'console_scripts', 'osbuild')())
  File "/usr/lib/python3.9/site-packages/osbuild/main_cli.py", line 137, in osbuild_cli
    r = manifest.build(
  File "/usr/lib/python3.9/site-packages/osbuild/pipeline.py", line 282, in build
    source.download(store, libdir)
  File "/usr/lib/python3.9/site-packages/osbuild/sources.py", line 55, in download
    raise RuntimeError(f"{source}: " + reply["error"])
RuntimeError: org.osbuild.curl: curl: error downloading {'url': 'https://localhost:8008/repo/Packages/n/NetworkManager-libnm-1.26.2-2.fc33.x86_64.rpm'}: error code 60
[root@rhelvm delve]# echo $?
1
```

**Comment by achilleas-k** [comment]
Is this a duplicate of #1378?

**Comment by msehnout** [comment]
Yes, it is.
