### ISSUE TITLE
osbuild ci: `fedora_32-x86_64-vmdk-boot.json`: Fedora 32 is EOL and thus not on the mirrors anymore

### ISSUE THREAD

**Issue by gicmo** [osbuild/osbuild-composer#1436]
```
[2021-06-01T09:49:59.110Z] stdout:
[2021-06-01T09:49:59.111Z] 
[2021-06-01T09:49:59.111Z] stderr:
[2021-06-01T09:49:59.111Z] Traceback (most recent call last):
[2021-06-01T09:49:59.111Z]   File "/usr/bin/osbuild", line 11, in <module>
[2021-06-01T09:49:59.111Z]     load_entry_point('osbuild==28', 'console_scripts', 'osbuild')()
[2021-06-01T09:49:59.111Z]   File "/usr/lib/python3.8/site-packages/osbuild/main_cli.py", line 137, in osbuild_cli
[2021-06-01T09:49:59.111Z]     r = manifest.build(
[2021-06-01T09:49:59.111Z]   File "/usr/lib/python3.8/site-packages/osbuild/pipeline.py", line 275, in build
[2021-06-01T09:49:59.111Z]     source.download(store, libdir)
[2021-06-01T09:49:59.111Z]   File "/usr/lib/python3.8/site-packages/osbuild/sources.py", line 54, in download
[2021-06-01T09:49:59.111Z]     raise RuntimeError(f"{source}: " + reply["error"])
[2021-06-01T09:49:59.111Z] RuntimeError: org.osbuild.curl: curl: error downloading {'url': 'http://mirrors.kernel.org/fedora/releases/32/Everything/x86_64/os/Packages/l/linux-firmware-20200316-106.fc32.noarch.rpm'}: error code 28
[2021-06-01T09:49:59.111Z]     main_test.go:479: 
[2021-06-01T09:49:59.111Z]         	Error Trace:	main_test.go:479
[2021-06-01T09:49:59.111Z]         	            				main_test.go:533
[2021-06-01T09:49:59.111Z]         	Error:      	Received unexpected error:
[2021-06-01T09:49:59.111Z]         	            	running osbuild failed: exit status 1
[2021-06-01T09:49:59.111Z]         	Test:       	TestImages/fedora_32-x86_64-vmdk-boot.json
[2021-06-01T09:49:59.111Z] --- FAIL: TestImages (359.35s)
[2021-06-01T09:49:59.111Z]     --- FAIL: TestImages/fedora_32-x86_64-vmdk-boot.json (359.31s)
[2021-06-01T09:49:59.111Z] FAIL
```

**Comment by gicmo** [comment]
Actually, it seems the files are still on the server, they just failed to download during the CI run.
