### ISSUE TITLE
base tests for F33 should use rpmrepo

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1551]
See https://gitlab.com/osbuild/ci/osbuild-composer/-/pipelines/336477721

```
Jul 14 07:05:53 ip-172-31-79-82.ec2.internal osbuild-worker[14548]: Traceback (most recent call last):
Jul 14 07:05:53 ip-172-31-79-82.ec2.internal osbuild-worker[14548]:   File "/usr/bin/osbuild", line 33, in <module>
Jul 14 07:05:53 ip-172-31-79-82.ec2.internal osbuild-worker[14548]:     sys.exit(load_entry_point('osbuild==28', 'console_scripts', 'osbuild')())
Jul 14 07:05:53 ip-172-31-79-82.ec2.internal osbuild-worker[14548]:   File "/usr/lib/python3.9/site-packages/osbuild/main_cli.py", line 137, in osbuild_cli
Jul 14 07:05:53 ip-172-31-79-82.ec2.internal osbuild-worker[14548]:     r = manifest.build(
Jul 14 07:05:53 ip-172-31-79-82.ec2.internal osbuild-worker[14548]:   File "/usr/lib/python3.9/site-packages/osbuild/pipeline.py", line 282, in build
Jul 14 07:05:53 ip-172-31-79-82.ec2.internal osbuild-worker[14548]:     source.download(store, libdir)
Jul 14 07:05:53 ip-172-31-79-82.ec2.internal osbuild-worker[14548]:   File "/usr/lib/python3.9/site-packages/osbuild/sources.py", line 55, in download
Jul 14 07:05:53 ip-172-31-79-82.ec2.internal osbuild-worker[14548]:     raise RuntimeError(f"{source}: " + reply["error"])
Jul 14 07:05:53 ip-172-31-79-82.ec2.internal osbuild-worker[14548]: RuntimeError: org.osbuild.curl: curl: error downloading {'url': 'https://mirrors.rit.edu/fedora/fedora/linux/updates/33/Everything/aarch64/Packages/l/libeconf-0.4.0-1.fc33.aarch64.rpm'}: error code 22
Jul 14 07:05:53 ip-172-31-79-82.ec2.internal osbuild-worker[14231]: 2021/07/14 07:05:53 Job 29dbb009-be8c-433e-89c0-8c9a00c5ad11 failed: error decoding osbuild output: unexpected end of JSON input
```

**Comment by teg** [comment]
Fixed by #1548.

**Comment by ondrejbudai** [comment]
#1548 actually covered only the image tests, base tests for aarch64 are actually still using the official metalink, see https://github.com/osbuild/osbuild-composer/blob/648bf26fcaa8d155561603240752516b8c0fa6b4/repositories/fedora-33.json#L33

**Comment by teg** [comment]
Thanks for reopening! I should have known you would have closed it if it was truly done ;)
