### ISSUE TITLE
No RockyLinux and AlmaLinux support

### ISSUE THREAD

**Issue by oducrot** [osbuild/osbuild-composer#1615]
**Describe the bug**
Using Rocky Linux 8.4
the first step after installation fails with a Python error:

`composer-cli status show`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.26.6-py3.6.egg/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.26.6-py3.6.egg/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.26.6-py3.6.egg/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1361, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/composer-cli", line 93, in <module>
    sys.exit(main(opts))
  File "/usr/lib/python3.6/site-packages/composer/cli/__init__.py", line 68, in main
    result = client.get_url_json(opts.socket, "/api/status")
  File "/usr/lib/python3.6/site-packages/composer/http_client.py", line 93, in get_url_json
    r = http.request("GET", url)
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.26.6-py3.6.egg/urllib3/request.py", line 75, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.26.6-py3.6.egg/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.26.6-py3.6.egg/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.26.6-py3.6.egg/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.26.6-py3.6.egg/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.26.6-py3.6.egg/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.26.6-py3.6.egg/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.26.6-py3.6.egg/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1361, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

Analyzing logs shows that osbuild-composer fails because that rocky linux appears as an unknown distro

```
Aug  3 23:14:04 ansible systemd[1]: Started User Manager for UID 0.
Aug  3 23:16:10 ansible systemd[1]: Reloading.
Aug  3 23:16:10 ansible systemd[1]: Starting OSBuild Composer Weldr API socket.
Aug  3 23:16:10 ansible systemd[1]: Listening on OSBuild Composer Weldr API socket.
Aug  3 23:16:17 ansible systemd[1]: Listening on OSBuild local worker API socket.
Aug  3 23:16:17 ansible systemd[1]: Started OSBuild Composer.
Aug  3 23:16:17 ansible systemd[1]: Started OSBuild Composer Worker (1).
Aug  3 23:16:17 ansible osbuild-composer[52304]: 2021/08/03 23:16:17 Loaded configuration:
Aug  3 23:16:17 ansible osbuild-composer[52304]: [koji]Aug  3 23:16:17 ansible osbuild-composer[52304]:  ca = ""
Aug  3 23:16:17 ansible osbuild-composer[52304]: [worker]Aug  3 23:16:17 ansible osbuild-composer[52304]:  ca = ""
Aug  3 23:16:17 ansible osbuild-composer[52304]: 2021/08/03 23:16:17 Error initializing weldr API: unknown distro: rocky-8
Aug  3 23:16:17 ansible systemd[1]: osbuild-composer.service: Main process exited, code=exited, status=1/FAILURE
Aug  3 23:16:17 ansible systemd[1]: osbuild-composer.service: Failed with result 'exit-code'.
Aug  3 23:16:17 ansible osbuild-worker[52305]: Waiting for a new job...
```
--

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`):
```
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

 * osbuild-composer version (`rpm -qi osbuild-composer)`
```
Name        : osbuild-composer
Version     : 28.6
Release     : 1.el8_4
Architecture: x86_64
Install Date: Sun 18 Jul 2021 08:53:53 AM CEST
Group       : Unspecified
Size        : 17237
License     : ASL 2.0
Signature   : RSA/SHA256, Wed 30 Jun 2021 10:29:51 AM CEST, Key ID 15af5dac6d745a60
Source RPM  : osbuild-composer-28.6-1.el8_4.src.rpm
Build Date  : Wed 30 Jun 2021 10:22:00 AM CEST
Build Host  : ord1-prod-x86build001.svc.aws.rockylinux.org
Relocations : (not relocatable)
```

**To Reproduce**
 * *for example starting osbuild-composer.service or running composer-cli command, don't forget to include all configuration files you created*
```
dnf install osbuild-composer composer-cli
systemctl enable --now osbuild-composer.socket
composer-cli status show
```

**Expected behavior**

```
RockyLinux support like CentOS 8, CentOS Stream, Fedora 34, etc
```

**Additional context**

```
The same error occurs with AlmaLinux 8.4
```

**Comment by ondrejbudai** [comment]
Hello, thanks for your report, we are already tracking this in issue #1411 so I'm closing this one. If you have more thoughts on this topic, feel free to continue the discussion on the other issue.
