### ISSUE TITLE
edge-simplified-installer pr #1654 failed to build edge-installer image

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#1669]
This bug is against #1654 , but not the main branch.

**Describe the bug**
I tried to build an edge-installer image with pr #1654 , but failed. The output of osbuild-worker is:

Aug 24 21:49:12 85iso2 osbuild-worker[35529]: Waiting for a new job...
Aug 24 21:54:32 85iso2 osbuild-worker[35529]: Running 'osbuild' job a1b51e13-edf8-4182-b7bc-5904c68e6c89
Aug 24 21:54:51 85iso2 osbuild-worker[35529]: Traceback (most recent call last):
Aug 24 21:54:51 85iso2 osbuild-worker[35529]:   File "/usr/bin/osbuild", line 11, in <module>
Aug 24 21:54:51 85iso2 osbuild-worker[35529]:     load_entry_point('osbuild==30', 'console_scripts', 'osbuild')()
Aug 24 21:54:51 85iso2 osbuild-worker[35529]:   File "/usr/lib/python3.6/site-packages/osbuild/main_cli.py", line 141, in osbuild_cli
Aug 24 21:54:51 85iso2 osbuild-worker[35529]:     output_directory=output_directory
Aug 24 21:54:51 85iso2 osbuild-worker[35529]:   File "/usr/lib/python3.6/site-packages/osbuild/pipeline.py", line 348, in build
Aug 24 21:54:51 85iso2 osbuild-worker[35529]:     source.download(store, libdir)
Aug 24 21:54:51 85iso2 osbuild-worker[35529]:   File "/usr/lib/python3.6/site-packages/osbuild/sources.py", line 54, in download
Aug 24 21:54:51 85iso2 osbuild-worker[35529]:     raise RuntimeError(f"{source}: " + reply["error"])
Aug 24 21:54:51 85iso2 osbuild-worker[35529]: RuntimeError: org.osbuild.curl: curl: error downloading {'url': 'http://download.eng.bos.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.5.0/compose/BaseOS/x86_64/os/Packages/glibc-langpack-en-2.28-162.el8.x86_64.rpm'}: error code 22
Aug 24 21:54:51 85iso2 osbuild-worker[35529]: 2021/08/24 21:54:51 Job a1b51e13-edf8-4182-b7bc-5904c68e6c89 failed: error decoding osbuild output: unexpected end of JSON input
Aug 24 21:54:51 85iso2 osbuild-worker[35529]: the raw output:
Aug 24 21:54:51 85iso2 osbuild-worker[35529]: Waiting for a new job...

I checked this url, it is 404. Seems osbuild is trying to get this package from a wrong place. Maybe this problem is related to the files under /etc/osbuild-composer/repositories?

**Environment**
As same as #1660 

**To Reproduce**
1. Build an edge-installer image
[root@85iso2 workspace]# composer-cli compose start-ostree installer edge-installer --ref rhel/8/x86_64/edge --url http://192.168.200.1/repo/
2. Failed.

**Expected behavior**
Should be able to build edge-installer image successfully.

**Additional context**

**Comment by yih-redhat** [comment]
This is caused by nightly sync issue, after changed to rpmrepo, it works now.
Closing this bug.
