### ISSUE TITLE
weldr api crash in composelogshandler

### ISSUE THREAD

**Issue by Gundersanne** [osbuild/osbuild-composer#2002]
**Describe the bug**
nil point deref

```
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]: 2021/11/11 10:27:05 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]: goroutine 499 [running]:
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]: net/http.(*conn).serve.func1(0xc0001841e0)
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]:         /usr/lib/golang/src/net/http/server.go:1804 +0x153
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]: panic(0x561bd0fa6420, 0x561bd1483130)
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]:         /usr/lib/golang/src/runtime/panic.go:971 +0x499
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]: github.com/osbuild/osbuild-composer/internal/osbuild1.(*Result).Write(0x0, 0x561bd1099938, 0xc000202600, 0x561bd109b898, 0xc000224380)
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]:         /builddir/build/BUILD/osbuild-composer-33.2/_build/src/github.com/osbuild/osbuild-composer/internal/osbuild1/result.go:87 +0x3c
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]: github.com/osbuild/osbuild-composer/internal/weldr.(*API).composeLogsHandler(0xc000125680, 0x561bd10a7d90, 0xc000224380, 0xc000252e00, 0xc000104d00, 0x2, 0x4)
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]:         /builddir/build/BUILD/osbuild-composer-33.2/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:2990 +0x965
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]: github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00007c540, 0x561bd10a7d90, 0xc000224380, 0xc000252e00)
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]:         /builddir/build/BUILD/osbuild-composer-33.2/_build/src/github.com/osbuild/osbuild-composer/vendor/github.com/julienschmidt/httprouter/router.go:387 +0xc7e
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]: github.com/osbuild/osbuild-composer/internal/weldr.(*API).ServeHTTP(0xc000125680, 0x561bd10a7d90, 0xc000224380, 0xc000252e00)
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]:         /builddir/build/BUILD/osbuild-composer-33.2/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:281 +0x13e
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]: net/http.serverHandler.ServeHTTP(0xc000126000, 0x561bd10a7d90, 0xc000224380, 0xc000252e00)
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]:         /usr/lib/golang/src/net/http/server.go:2867 +0xa5
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]: net/http.(*conn).serve(0xc0001841e0, 0x561bd10aacb0, 0xc00019cec0)
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]:         /usr/lib/golang/src/net/http/server.go:1932 +0x8cd
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]: created by net/http.(*Server).Serve
Nov 11 10:27:05 localhost.localdomain osbuild-composer[15133]:         /usr/lib/golang/src/net/http/server.go:2993 +0x3ad
```

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): rhel-85
 * osbuild-composer version (`rpm -qi osbuild-composer)` v33.2

**To Reproduce**

 blueprint
```
name = "edge-device"
description = "RHEL for Edge"
version = "0.0.1"
modules = []
groups = []
distro = ""

[[packages]]
name = "yggdrasil"
version = "*"

[[packages]]
name = "k4e-agent"
version = "*"

[[packages]]
name = "dmidecode"
version = "*"

[[packages]]
name = "ipmitool"
version = "*"

[[packages]]
name = "smartmontools"
version = "*"

[[packages]]
name = "file"
version = "*"

[[packages]]
name = "util-linux"
version = "*"
```

`composer-cli compose start edge-device edge-commit`

**Comment by achilleas-k** [comment]
Is this fixed by #1754?

If it's not, it probably moved to https://github.com/osbuild/osbuild-composer/blob/b075cac9e3d4a283918dbefa66cce46d372e3835/internal/osbuild2/result.go#L204 instead.
