### ISSUE TITLE
composer-cli compose status FAILED

### ISSUE THREAD

**Issue by husky-parul** [osbuild/osbuild-composer#2224]
**Describe the bug**
Building image using `sudo composer-cli compose start ` is failing

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): Fedora 35
 ```
  uname -r
  5.15.12-200.fc35.x86_64
```

 * osbuild-composer version (`rpm -qi osbuild-composer)`
```
sudo rpm -qi osbuild-composer
Name        : osbuild-composer
Version     : 42
Release     : 1.fc35
Architecture: x86_64
Install Date: Wed 26 Jan 2022 03:08:09 PM EST
Group       : Unspecified
Size        : 17577
License     : ASL 2.0
Signature   : RSA/SHA256, Wed 12 Jan 2022 08:59:40 AM EST, Key ID db4639719867c58f
Source RPM  : osbuild-composer-42-1.fc35.src.rpm
Build Date  : Wed 12 Jan 2022 08:53:03 AM EST
Build Host  : buildvm-x86-17.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/osbuild/osbuild-composer
Bug URL     : https://bugz.fedoraproject.org/osbuild-composer
Summary     : An image building service based on osbuild
```
**To Reproduce**
[Create the OSTree in Image Builder command line ](https://www.osbuild.org/news/2020-06-01-how-to-ostree-anaconda.html)
iot.toml
```
name = "iot"
description = ""
version = "0.0.0"
packages = []
modules = []
groups = []

sudo composer-cli blueprints push iot.toml
sudo composer-cli compose start iot fedora-iot-commit

sudo composer-cli compose status
528cb533-1beb-4e5a-acb8-61e4ba5feb33 RUNNING  Wed Jan 26 15:42:51 2022 iot             0.0.0 fedora-iot-commit 

sudo composer-cli compose status
528cb533-1beb-4e5a-acb8-61e4ba5feb33 FAILED   Wed Jan 26 15:42:59 2022 iot             0.0.0 fedora-iot-commit 
```
I extracted the logs
```
cat logs/osbuild.log 
The compose result is empty.
```

**Expected behavior**

**Additional context**

**Comment by thozza** [comment]
Hi @husky-parul.

Sorry for the late response. I just tested this scenario on F35, but the osbuild-composer available in the repositories is already of version 47.

Could you please confirm that you are still seeing this issue?

If yes, could you please provide the following additional information?

- output of `journalctl -b -u '*osbuild*'`
- content of the latest `<uuid>.json` file from `/var/lib/osbuild-composer/jobs/` directory. The filename us based on the job UUID and unfortunately does not correspond with the compose UUID, so you'll have to pinpoint the file by its modification time.
- file created by `composer-cli compose metadata <UUID>`
- file created by `composer-cli compose logs <UUID>` (I know that you mentioned that logs were empty)
- file created by `composer-cli compose results <UUID>`

Thanks in advance!

**Comment by 4383** [comment]
Hello,

I face the same issue, I'm using fedora 36, and I can see the following error when I display the `journalctl` for osbuild:

```
juin 06 18:29:45 fedora osbuild-worker[26636]: time="2023-06-06T18:29:45+02:00" level=info msg="Running job '622583dc-a5c3-4d2a-b46e-456c3d43cc6f' (osbuild)\n"
juin 06 18:30:19 fedora python3[29273]: detected unhandled Python exception in '/usr/bin/osbuild'
juin 06 18:30:19 fedora osbuild-worker[29273]: Traceback (most recent call last):
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/bin/osbuild", line 33, in <module>
juin 06 18:30:19 fedora osbuild-worker[29273]:     sys.exit(load_entry_point('osbuild==83', 'console_scripts', 'osbuild')())
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib/python3.10/site-packages/osbuild/main_cli.py", line 163, in osbuild_cli
juin 06 18:30:19 fedora osbuild-worker[29273]:     manifest.download(object_store, monitor, args.libdir)
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib/python3.10/site-packages/osbuild/pipeline.py", line 409, in download
juin 06 18:30:19 fedora osbuild-worker[29273]:     source.download(mgr, store, libdir)
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib/python3.10/site-packages/osbuild/sources.py", line 41, in download
juin 06 18:30:19 fedora osbuild-worker[29273]:     reply = client.call_with_fds("download", args, fds)
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib/python3.10/site-packages/osbuild/host.py", line 384, in call_with_fds
juin 06 18:30:19 fedora osbuild-worker[29273]:     raise error
juin 06 18:30:19 fedora osbuild-worker[29273]: osbuild.host.RemoteError: RuntimeError: curl: error downloading http://mirror.in2p3.fr/pub/fedora/linux/releases/36/Everything/x86_64/os/Packages/l/libmodulemd-2.14.0-2.fc36.x86_64.rpm: error>
juin 06 18:30:19 fedora osbuild-worker[29273]:    File "/usr/lib/python3.10/site-packages/osbuild/host.py", line 268, in serve
juin 06 18:30:19 fedora osbuild-worker[29273]:     reply, reply_fds = self._handle_message(msg, fds)
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib/python3.10/site-packages/osbuild/host.py", line 301, in _handle_message
juin 06 18:30:19 fedora osbuild-worker[29273]:     ret, fds = self.dispatch(name, args, fds)
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib/python3.10/site-packages/osbuild/sources.py", line 106, in dispatch
juin 06 18:30:19 fedora osbuild-worker[29273]:     self.download(SourceService.load_items(fds))
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib/python3.10/site-packages/osbuild/sources.py", line 82, in download
juin 06 18:30:19 fedora osbuild-worker[29273]:     for _ in executor.map(self.fetch_one, *zip(*transformed)):
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
juin 06 18:30:19 fedora osbuild-worker[29273]:     yield _result_or_cancel(fs.pop())
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
juin 06 18:30:19 fedora osbuild-worker[29273]:     return fut.result(timeout)
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 458, in result
juin 06 18:30:19 fedora osbuild-worker[29273]:     return self.__get_result()
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 403, in __get_result
juin 06 18:30:19 fedora osbuild-worker[29273]:     raise self._exception
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
juin 06 18:30:19 fedora osbuild-worker[29273]:     result = self.fn(*self.args, **self.kwargs)
juin 06 18:30:19 fedora osbuild-worker[29273]:   File "/usr/lib/osbuild/sources/org.osbuild.curl", line 158, in fetch_one
juin 06 18:30:19 fedora osbuild-worker[29273]:     raise RuntimeError(f"curl: error downloading {url}: error code {return_code}")
juin 06 18:30:19 fedora osbuild-worker[26636]: time="2023-06-06T18:30:19+02:00" level=error msg="osbuild job failed: osbuild build failed" jobId=622583dc-a5c3-4d2a-b46e-456c3d43cc6f
juin 06 18:30:19 fedora osbuild-worker[26636]: time="2023-06-06T18:30:19+02:00" level=warning msg="Job '622583dc-a5c3-4d2a-b46e-456c3d43cc6f' (osbuild) failed: error decoding osbuild output: unexpected end of JSON input\nthe raw output:\n"
```

I can see similar errors in the logs each time I run the command `composer-cli compose start `.

For more context about my builds, I followed the instructions given in this blog post https://major.io/2022/05/06/build-a-custom-centos-stream-9-cloud-image/

Does that ring some bells on your side?

Hervé

**Comment by 4383** [comment]
I think the real issue is:

```
osbuild.host.RemoteError: RuntimeError: curl: error downloading http://mirror.in2p3.fr/pub/fedora/linux/releases/36/Everything/x86_64/os/Packages/d/device-mapper-libs-1.02.175-7.fc36.x86_64.>
```

This url doesn't exist (404 not found) => http://mirror.in2p3.fr/pub/fedora/linux/releases/36/Everything/x86_64/os/Packages/d/device-mapper-libs-1.02.175-7.fc36.x86_64

However, I don't how osbuilder determine the url of this mirror, apparently it is based on the `host.py` module of the osbuilder package...

**Comment by 4383** [comment]
Fedora 36 is not listed in this mirror http://mirror.in2p3.fr/linux.html

I can't find the place where the osbuild environment define or retrieve this mirror, do you have any idea?

**Comment by 4383** [comment]
Also we should notice that fedora 35 is not listed either, so may @husky-parul faced the same issue than me with the mirror.

**Comment by thozza** [comment]
Hi.

Fedora 36 is already EOL. When you start Fedora image build, osbuild-composer will produce a manifest for `osbuild`. This includes depsolving the package set for the image using repositories from `/usr/share/osbuild-composer/repositories` which look like this (for F37) https://github.com/osbuild/osbuild-composer/blob/main/repositories/fedora-37.json#L5 The repo URL is a mirror list, so an URL pointing to the specific RPM depends on the actual mirror that DNF picks when depsolving the image package set.

What could have happened is that you've depsolved the image package set in the past, when the mirror contained F36 repositories, but since F36 is already EOL, the repository is gone from the mirror.

Depsolving is done on each new compose request AFAICT, so DNF should pick new mirror which has F36 repos available. So in theory, this should not be happening consistently.

I would suggest to move to supported Fedora version and if the issue persist, reach out back. Sorry for not having a better answer.

**Comment by 4383** [comment]
Well, I upgraded my system to fedora 38 and more or less the same error (mirror not found) is still there.

We can see that osbuild try to download mirror for fedora 38 which is correct, however, the download return an error 22 (I don't the meaning of error 22) but I've no problem to download it manually  http://mirror.in2p3.fr/pub/fedora/linux/updates/38/Everything/x86_64/Packages/s/sssd-kcm-2.9.0-1.fc38.x86_64.rpm

```
juin 07 16:11:31 fedora osbuild-worker[27067]: time="2023-06-07T16:11:31+02:00" level=info msg="Running job '90c2d9be-cd21-4d22-ab38-2d261dc60737' (osbuild)\n"
juin 07 16:11:34 fedora python3[29758]: detected unhandled Python exception in '/usr/bin/osbuild'
juin 07 16:11:34 fedora osbuild-worker[29758]: Traceback (most recent call last):
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/bin/osbuild", line 33, in <module>
juin 07 16:11:34 fedora osbuild-worker[29758]:     sys.exit(load_entry_point('osbuild==86', 'console_scripts', 'osbuild')())
juin 07 16:11:34 fedora osbuild-worker[29758]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib/python3.11/site-packages/osbuild/main_cli.py", line 163, in osbuild_cli
juin 07 16:11:34 fedora osbuild-worker[29758]:     manifest.download(object_store, monitor, args.libdir)
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib/python3.11/site-packages/osbuild/pipeline.py", line 409, in download
juin 07 16:11:34 fedora osbuild-worker[29758]:     source.download(mgr, store, libdir)
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib/python3.11/site-packages/osbuild/sources.py", line 40, in download
juin 07 16:11:34 fedora osbuild-worker[29758]:     reply = client.call_with_fds("download", args, fds)
juin 07 16:11:34 fedora osbuild-worker[29758]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib/python3.11/site-packages/osbuild/host.py", line 384, in call_with_fds
juin 07 16:11:34 fedora osbuild-worker[29758]:     raise error
juin 07 16:11:34 fedora osbuild-worker[29758]: osbuild.host.RemoteError: RuntimeError: curl: error downloading http://mirror.in2p3.fr/pub/fedora/linux/updates/38/Everything/x86_64/Packages/s/sssd-kcm-2.9.0-1.fc38.x86_64.rpm: error code 22
juin 07 16:11:34 fedora osbuild-worker[29758]:    File "/usr/lib/python3.11/site-packages/osbuild/host.py", line 268, in serve
juin 07 16:11:34 fedora osbuild-worker[29758]:     reply, reply_fds = self._handle_message(msg, fds)
juin 07 16:11:34 fedora osbuild-worker[29758]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib/python3.11/site-packages/osbuild/host.py", line 301, in _handle_message
juin 07 16:11:34 fedora osbuild-worker[29758]:     ret, fds = self.dispatch(name, args, fds)
juin 07 16:11:34 fedora osbuild-worker[29758]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib/python3.11/site-packages/osbuild/sources.py", line 102, in dispatch
juin 07 16:11:34 fedora osbuild-worker[29758]:     self.download(SourceService.load_items(fds))
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib/python3.11/site-packages/osbuild/sources.py", line 84, in download
juin 07 16:11:34 fedora osbuild-worker[29758]:     for _ in executor.map(self.fetch_one, *zip(*transformed)):
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
juin 07 16:11:34 fedora osbuild-worker[29758]:     yield _result_or_cancel(fs.pop())
juin 07 16:11:34 fedora osbuild-worker[29758]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
juin 07 16:11:34 fedora osbuild-worker[29758]:     return fut.result(timeout)
juin 07 16:11:34 fedora osbuild-worker[29758]:            ^^^^^^^^^^^^^^^^^^^
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 456, in result
juin 07 16:11:34 fedora osbuild-worker[29758]:     return self.__get_result()
juin 07 16:11:34 fedora osbuild-worker[29758]:            ^^^^^^^^^^^^^^^^^^^
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 401, in __get_result
juin 07 16:11:34 fedora osbuild-worker[29758]:     raise self._exception
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib64/python3.11/concurrent/futures/thread.py", line 58, in run
juin 07 16:11:34 fedora osbuild-worker[29758]:     result = self.fn(*self.args, **self.kwargs)
juin 07 16:11:34 fedora osbuild-worker[29758]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
juin 07 16:11:34 fedora osbuild-worker[29758]:   File "/usr/lib/osbuild/sources/org.osbuild.curl", line 158, in fetch_one
juin 07 16:11:34 fedora osbuild-worker[29758]:     raise RuntimeError(f"curl: error downloading {url}: error code {return_code}")
juin 07 16:11:34 fedora osbuild-worker[27067]: time="2023-06-07T16:11:34+02:00" level=error msg="osbuild job failed: osbuild build failed" jobId=90c2d9be-cd21-4d22-ab38-2d261dc60737
juin 07 16:11:34 fedora osbuild-worker[27067]: time="2023-06-07T16:11:34+02:00" level=warning msg="Job '90c2d9be-cd21-4d22-ab38-2d261dc60737' (osbuild) failed: error decoding osbuild output: unexpected end of JSON input\nthe raw output:\n"
```

Thoughts?

**Comment by bcl** [comment]
curl error code 22 means the server returned an error code > 400 but it isn't more specific than that.

I'm working on a new source method that should help in cases like this (it uses librepo to try the other mirrors when things fail) but it's not ready yet.

I suspect that the server is returning errors sometimes, but not always, so you end up hitting a download failure at some point when it is fetching the rpms.

You can try replacing the repository json with a baseurl instead of a mirror:
* Copy `/usr/share/osbuild-composer/repositories/fedora-38.json` to `/etc/osbuild-composer/repositories/`
* Edit the file to change the `metalink` to `baseurl` and your selected mirror (not the one that is failing, I suspect it has intermittent issues)
* Remove `/var/cache/osbuild-composer/rpmmd/` and reboot.

**Comment by 4383** [comment]
Thanks @bcl I'll try to do that.

**Comment by thozza** [comment]
Closing this issue, since the original reporter didn't provide the requested information. Moreover, F35 is already EOL.
