### ISSUE TITLE
dnf-json: error unhandled if dependency cannot be found

### ISSUE THREAD

**Issue by teg** [osbuild/osbuild-composer#2839]
If the dependency of a package cannot be found (for instance if not all repositories that should be attached to the compose request have been), we should return a helpful error message. Currently we return `""`.

**Comment by teg** [comment]
See https://github.com/osbuild/osbuild-composer/pull/2838#issuecomment-1186290659

cc @achilleas-k @ondrejbudai @Gundersanne

**Comment by Gundersanne** [comment]
I think this is due to dnf-json crashing when constructing the actual error message:

```
time="2022-06-08T15:10:59Z" level=info msg="Job 'aa7138e2-c3a4-491b-8aea-5d0a55282ab0' (depsolve) finished"                                                                                                                           |
| time="2022-06-08T15:10:59Z" level=error msg="rpmmd error in depsolve job: DNF error occurred: InternalError: Failed to unmarshal dnf-json error output \"\": unexpected end of JSON input" jobId=aa7138e2-c3a4-491b-8aea-5d0a55282ab0 |
| Traceback (most recent call last):                                                                                                                                                                                                    |
|   File "/usr/libexec/osbuild-composer/dnf-json", line 205, in solve                                                                                                                                                                   |
|     result = solver.depsolve(transactions)                                                                                                                                                                                            |
|   File "/usr/libexec/osbuild-composer/dnf-json", line 140, in depsolve                                                                                                                                                                |
|     self.base.resolve()                                                                                                                                                                                                               |
|   File "/usr/lib/python3.6/site-packages/dnf/base.py", line 860, in resolve                                                                                                                                                           |
|     raise exc                                                                                                                                                                                                                         |
| dnf.exceptions.DepsolveError:                                                                                                                                                                                                         |
|  Problem: conflicting requests                                                                                                                                                                                                        |
|   - package packit-0.52.0-1.el8.noarch requires python3-packit = 0.52.0-1.el8, but none of the providers can be installed                                                                                                             |
|   - package packit-0.52.1-1.el8.noarch requires python3-packit = 0.52.1-1.el8, but none of the providers can be installed                                                                                                             |
|   - nothing provides python3.6dist(packaging) needed by python3-packit-0.52.0-1.el8.noarch                                                                                                                                            |
|   - nothing provides python3.6dist(packaging) needed by python3-packit-0.52.1-1.el8.noarch                                                                                                                                            |
| During handling of the above exception, another exception occurred:                                                                                                                                                                   |
| Traceback (most recent call last):                                                                                                                                                                                                    |
|   File "/usr/libexec/osbuild-composer/dnf-json", line 300, in <module>                                                                                                                                                                |
|     main()                                                                                                                                                                                                                            |
|   File "/usr/libexec/osbuild-composer/dnf-json", line 292, in main                                                                                                                                                                    |
|     result, err = solve(request, cachedir)                                                                                                                                                                                            |
|   File "/usr/libexec/osbuild-composer/dnf-json", line 217, in solve                                                                                                                                                                   |
|     "reason": f"There was a problem depsolving {arguments['package-specs']}: {e}"                                                                                                                                                     |
| KeyError: 'package-specs'                                                                                                                                                                                                             |
```

**Comment by achilleas-k** [comment]
Got a weird deja vu from this and took me a minute to figure out.
This was fixed here https://github.com/osbuild/osbuild-composer/commit/d59d870574729c782783c91624f34cf580b25c96

**Comment by teg** [comment]
ah, but not deployed?

**Comment by Gundersanne** [comment]
Ah indeed, `fe918fd8a0099e8f3a82968362838714fafd9d41` currently on production  which is older.

**Comment by achilleas-k** [comment]
Closing this as solved.
