### ISSUE TITLE
OSBuild Composer is failing to depsolve

### ISSUE THREAD

**Issue by jkozol** [osbuild/osbuild-composer#3051]
In the cockpit-composer CI tests several api calls requiring depsolve are having issues. I believe this only occurs after service start on a fresh machine.

The weldr api takes minutes to return `/projects/` and `/modules/` api routes. And the `/blueprints/new` and  `/blueprints/depsolve` calls fail. with the following error:

```
Oct 06 13:17:19 vm osbuild-composer[1862]:         /usr/lib/golang/src/net/http/server.go:3071 +0x4db
Oct 06 13:17:19 vm osbuild-composer[1862]: created by net/http.(*Server).Serve
Oct 06 13:17:19 vm osbuild-composer[1862]:         /usr/lib/golang/src/net/http/server.go:1966 +0x5d7
Oct 06 13:17:19 vm osbuild-composer[1862]: net/http.(*conn).serve(0xc00047c500, {0x5587a926a688, 0xc00057a570})
Oct 06 13:17:19 vm osbuild-composer[1862]:         /usr/lib/golang/src/net/http/server.go:2916 +0x43b
Oct 06 13:17:19 vm osbuild-composer[1862]: net/http.serverHandler.ServeHTTP({0xc00057b440?}, {0x5587a92697b0, 0xc000167180}, 0xc00013ef00)
Oct 06 13:17:19 vm osbuild-composer[1862]:         /builddir/build/BUILD/osbuild-composer-64/_build/src/github.com/osbuild/osbuild-compose>
Oct 06 13:17:19 vm osbuild-composer[1862]: github.com/osbuild/osbuild-composer/internal/weldr.(*API).ServeHTTP(0xc00053edc0, {0x5587a92697>
Oct 06 13:17:19 vm osbuild-composer[1862]:         /builddir/build/BUILD/osbuild-composer-64/_build/src/github.com/osbuild/osbuild-compose>
Oct 06 13:17:19 vm osbuild-composer[1862]: github.com/osbuild/osbuild-composer/vendor/github.com/julienschmidt/httprouter.(*Router).ServeH>
Oct 06 13:17:19 vm osbuild-composer[1862]:         /builddir/build/BUILD/osbuild-composer-64/_build/src/github.com/osbuild/osbuild-compose>
Oct 06 13:17:19 vm osbuild-composer[1862]: github.com/osbuild/osbuild-composer/internal/weldr.(*API).blueprintsDepsolveHandler(0xc00053edc>
Oct 06 13:17:19 vm osbuild-composer[1862]:         /builddir/build/BUILD/osbuild-composer-64/_build/src/github.com/osbuild/osbuild-compose>
Oct 06 13:17:19 vm osbuild-composer[1862]: github.com/osbuild/osbuild-composer/internal/common.PanicOnError(...)
Oct 06 13:17:19 vm osbuild-composer[1862]:         /usr/lib/golang/src/runtime/panic.go:844 +0x258
Oct 06 13:17:19 vm osbuild-composer[1862]: panic({0x5587a913e000, 0xc00042c3c0})
Oct 06 13:17:19 vm osbuild-composer[1862]:         /usr/lib/golang/src/net/http/server.go:1825 +0xbf
Oct 06 13:17:19 vm osbuild-composer[1862]: net/http.(*conn).serve.func1()
Oct 06 13:17:19 vm osbuild-composer[1862]: goroutine 52 [running]:
Oct 06 13:17:19 vm osbuild-composer[1862]: 2022/10/06 13:17:19 http: panic serving @: write unix /run/weldr/api.socket->@: write: broken p>
Oct 06 13:17:19 vm osbuild-composer[1862]:         /usr/lib/golang/src/net/http/server.go:3071 +0x4db
Oct 06 13:17:19 vm osbuild-composer[1862]: created by net/http.(*Server).Serve
Oct 06 13:17:19 vm osbuild-composer[1862]:         /usr/lib/golang/src/net/http/server.go:1966 +0x5d7
Oct 06 13:17:19 vm osbuild-composer[1862]: net/http.(*conn).serve(0xc00047c140, {0x5587a926a688, 0xc00057a570})
Oct 06 13:17:19 vm osbuild-composer[1862]:         /usr/lib/golang/src/net/http/server.go:2916 +0x43b
Oct 06 13:17:19 vm osbuild-composer[1862]: net/http.serverHandler.ServeHTTP({0xc00057a9c0?}, {0x5587a92697b0, 0xc000166000}, 0xc00013ed00)
Oct 06 13:17:19 vm osbuild-composer[1862]:         /builddir/build/BUILD/osbuild-composer-64/_build/src/github.com/osbuild/osbuild-compose>
Oct 06 13:17:19 vm osbuild-composer[1862]: github.com/osbuild/osbuild-composer/internal/weldr.(*API).ServeHTTP(0xc00053edc0, {0x5587a92697>
Oct 06 13:17:19 vm osbuild-composer[1862]:         /builddir/build/BUILD/osbuild-composer-64/_build/src/github.com/osbuild/osbuild-compose>
Oct 06 13:17:19 vm osbuild-composer[1862]: github.com/osbuild/osbuild-composer/vendor/github.com/julienschmidt/httprouter.(*Router).ServeH>
Oct 06 13:17:19 vm osbuild-composer[1862]:         /builddir/build/BUILD/osbuild-composer-64/_build/src/github.com/osbuild/osbuild-compose>
Oct 06 13:17:19 vm osbuild-composer[1862]: github.com/osbuild/osbuild-composer/internal/weldr.(*API).modulesInfoHandler(0xc00053edc0, {0x5>
Oct 06 13:17:19 vm osbuild-composer[1862]:         /builddir/build/BUILD/osbuild-composer-64/_build/src/github.com/osbuild/osbuild-compose>
Oct 06 13:17:19 vm osbuild-composer[1862]: github.com/osbuild/osbuild-composer/internal/common.PanicOnError(...)
Oct 06 13:17:19 vm osbuild-composer[1862]:         /usr/lib/golang/src/runtime/panic.go:844 +0x258
Oct 06 13:17:19 vm osbuild-composer[1862]: panic({0x5587a913e000, 0xc00042c280})
Oct 06 13:17:19 vm osbuild-composer[1862]:         /usr/lib/golang/src/net/http/server.go:1825 +0xbf
Oct 06 13:17:19 vm osbuild-composer[1862]: net/http.(*conn).serve.func1()
Oct 06 13:17:19 vm osbuild-composer[1862]: goroutine 49 [running]:
Oct 06 13:17:19 vm osbuild-composer[1862]: 2022/10/06 13:17:19 http: panic serving @: write unix /run/weldr/api.socket->@: write: broken pipe>
```

**Comment by bcl** [comment]
What version of osbuild-composer? This could be timeout related, initial metadata download can take a long time and if the client closes the connection due to a timeout you would get a broken pipe error.

**Comment by jkozol** [comment]
Version 64

**Comment by bcl** [comment]
Yeah, the first request on a fresh machine can take a few minutes depending on how fast the metadata is downloaded. Assuming it is using socket activation it will start osbuild-composer.service which will start the metadata download right away. It may be slightly faster to set it up to start the service by default, but if the test starts right away it probably doesn't matter. The initial request from the test needs to have a pretty long timeout on it, 5 minutes maybe. composer-cli has a default timeout of 240s FWIW.
