### ISSUE TITLE
CentOS Stream 8 with kernel-rt fails to generate manifest (non-edge)

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/osbuild-composer#3211]
Building a non-edge image with `kernel-rt` as the kernel fails to generate a manifest on CentOS Stream 8.

### Minimal example

```
$ composer-cli blueprints show rt
name = "rt"
description = ""
version = "0.0.2"
packages = []
modules = []
groups = []
distro = ""

[customizations]
[customizations.kernel]
name = "kernel-rt"
append = ""

$ composer-cli compose start rt qcow2
ERROR: Push TOML Error: Post "http://localhost/api/v1/compose": EOF
$ composer-cli compose start rt vhd
ERROR: Push TOML Error: Post "http://localhost/api/v1/compose": EOF
$ composer-cli compose start rt edge-commit
Compose 8cb9e4b9-b293-432c-9eb1-193a2377310b added to the queue
```

### Stacktrace
```
2023/01/12 21:23:50 http: panic serving @: package "kernel-rt" not found in the PackageSpec list
goroutine 373 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/golang/src/net/http/server.go:1850 +0xbf
panic({0x561c99f072c0, 0xc00024ae40})
        /usr/lib/golang/src/runtime/panic.go:890 +0x262
github.com/osbuild/osbuild-composer/internal/rpmmd.GetVerStrFromPackageSpecListPanic(...)
        /builddir/build/BUILD/osbuild-composer-70/_build/src/github.com/osbuild/osbuild-composer/internal/rpmmd/repository.go:193
github.com/osbuild/osbuild-composer/internal/distro/rhel8.osPipeline(0xc00058c5a0, {0xc0001d9680, 0x2, 0x0?}, {0xc000b56000?, 0x263, 0x263}, {0x561c9a871528, 0x0, 0x0}, ...)
        /builddir/build/BUILD/osbuild-composer-70/_build/src/github.com/osbuild/osbuild-composer/internal/distro/rhel8/pipelines.go:628 +0x5ad4
github.com/osbuild/osbuild-composer/internal/distro/rhel8.vhdPipelines.func1(0xc00058c5a0, 0xc0004a6210, {0x100000000, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
        /builddir/build/BUILD/osbuild-composer-70/_build/src/github.com/osbuild/osbuild-composer/internal/distro/rhel8/azure.go:267 +0x32b
github.com/osbuild/osbuild-composer/internal/distro/rhel8.(*imageType).Manifest(0xc00058c5a0, 0xc0004a6210, {0x100000000, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
        /builddir/build/BUILD/osbuild-composer-70/_build/src/github.com/osbuild/osbuild-composer/internal/distro/rhel8/distro.go:549 +0x1ea
github.com/osbuild/osbuild-composer/internal/weldr.(*API).composeHandler(0xc00037a180, {0x561c9a0a4ce8?, 0xc0001ee000}, 0xc0001b8000, {0xc000516120, 0x1, 0x3})
        /builddir/build/BUILD/osbuild-composer-70/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:2499 +0x1717
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00009c9c0, {0x561c9a0a4ce8, 0xc0001ee000}, 0xc0001b8000)
        /builddir/build/BUILD/osbuild-composer-70/_build/src/github.com/osbuild/osbuild-composer/vendor/github.com/julienschmidt/httprouter/router.go:387 +0x81c
github.com/osbuild/osbuild-composer/internal/weldr.(*API).ServeHTTP(0xc00037a180, {0x561c9a0a4ce8, 0xc0001ee000}, 0xc0001b8000)
        /builddir/build/BUILD/osbuild-composer-70/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:302 +0x16a
net/http.serverHandler.ServeHTTP({0x561c9a0a1708?}, {0x561c9a0a4ce8, 0xc0001ee000}, 0xc0001b8000)
        /usr/lib/golang/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc000380000, {0x561c9a0a5e20, 0xc0001ba0c0})
        /usr/lib/golang/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        /usr/lib/golang/src/net/http/server.go:3102 +0x4db
```

### Cause
CentOS Stream 8 does not include a `kernel-rt` package.  Depsolving for `kernel-rt` resolves to `kernel-rt-core`.
This cause the following line to fail, because it searches for `kernel-rt` and no package with that name exists in the package sets:
https://github.com/osbuild/osbuild-composer/blob/25faf5ab6088dbebfcc6c2706d6f91be74c0cf08/internal/distro/rhel8/pipelines.go#L628

This doesn't happen when building an `edge-commit` (or `edge-container`) because the search only runs when a partition table is defined, which we don't have for these image types.  In our tests, we only use `kernel-rt` in edge image types, to test for the multi-kernel limitation of ostree.

### Impact
The impact is pretty small.  It doesn't seem like this is a common use case and it can be worked around easily by specifying `kernel-rt-core` in the blueprint when building CS8 images.
It does however raise an interesting question about package naming.  We assume a package with the name defined in the kernel will be in the list because we depsolved for it, but what happens when we depsolve for a package named PACKAGE and the results don't include anything with that exact name?

This bug became an issue during the RHEL 8 rewrite because we search for the kernel package to get the version string even when building edge image types.

**Comment by thozza** [comment]
c8s is eol
