### ISSUE TITLE
sources API does not support proxy field

### ISSUE THREAD

**Issue by bcl** [osbuild/osbuild-composer#592]
The store has no storage for the proxy setting, so it is ignored. It should store it, and pass it to rpm/dnf along with the rest of the repository details.

**Comment by teg** [comment]
How high a priority is this? Is this about performance only, or would some usecases break? Either way it makes sense to me to add. Does it make sense to add this to composer to do the depsolving without also adding the same to osbuild to download the RPMs?

My gut feeling is that though this makes sense it isn't necessarily the highest priority?

**Comment by bcl** [comment]
I don't have any way to evaluate how important it is :) But I do know that certain users only use our tools via proxy with no direct access to the outside network. And personally I have a polipo cache setup locally that I use with Fedora content to speed things up on repeated runs.

**Comment by mattpielm** [comment]
My org has zero non-proxy access to external sites so it's not a simple performance issue. The tool unfortunately is dead in the water until this feature appears. As a possible solution, could the tool inspect the global proxy= settings in /etc/dnf/dnf.conf and allow the builder process use them directly or copy them into the repo files it's generating?

**Comment by mattpielm** [comment]
Update, got further by adding proxy environment to osbuild-composer.service so depsolve now works, but the compose process is calling curl without seeing the proxy env variables. I can see the SYN-SENT in ss -tn sessions going direct to an internet address.

- name: Set osbuild Proxy
  blockinfile:
    path: "/usr/lib/systemd/system/osbuild-composer.service"
    backup: yes
    create: yes
    mode: 0644
    insertafter: "^Environment="
    block: |
      Environment="HTTP_PROXY=http://{{ PROXY }}:{{ PROXY_PORT }}"
      Environment="HTTPS_PROXY=http://{{ PROXY }}:{{ PROXY_PORT }}"
      Environment="NO_PROXY=http://{{ PROXY }}:{{ PROXY_PORT }}"
      Environment="http_proxy=http://{{ PROXY }}:{{ PROXY_PORT }}"
      Environment="https_proxy=http://{{ PROXY }}:{{ PROXY_PORT }}"
      Environment="no_proxy=http://{{ PROXY }}:{{ PROXY_PORT }}"

**Comment by mattpielm** [comment]
Output bug:
Output:
[/usr/lib/tmpfiles.d/journal-nocow.conf:26] Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
[/usr/lib/tmpfiles.d/rpcbind.conf:2] Unknown user 'rpc'.
[/usr/lib/tmpfiles.d/setroubleshoot.conf:1] Unknown user 'setroubleshoot'.
Failed to create file /sys/fs/selinux/checkreqprot: Read-only file system
imported gpg key
imported gpg key
fetching sources
Traceback (most recent call last):
  File "/run/osbuild/lib/stages/org.osbuild.rpm", line 161, in <module>
    r = main(args["tree"], args["sources"], args["options"])
  File "/run/osbuild/lib/stages/org.osbuild.rpm", line 101, in main
    osbuild.sources.get("org.osbuild.files", checksums)
  File "/run/osbuild/lib/osbuild/sources.py", line 87, in get
    raise RuntimeError(f"{source}: " + reply["error"])
RuntimeError: org.osbuild.files: curl: error downloading {'url': 'https://cdn.redhat.com/content/dist/rhel8/8/x86_64/baseos/os/Packages/l/libevent-2.1.8-5.el8.x86_64.rpm', 'secrets': {'ssl_ca_cert': '/etc/rhsm/ca/redhat-uep.pem', 'ssl_client_key': '/etc/pki/entitlement/516878095454885961-key.pem', 'ssl_client_cert': '/etc/pki/entitlement/516878095454885961.pem'}}: error code 28

I tried one of the curl commands cut-n-paste into my shell and it worked fine, so it's likely that my shell has the proxy env set.

**Comment by teg** [comment]
@mattpielm thanks for your report. As a work-around, are you able to insert the same env vars in `/usr/lib/systemd/system/osbuild-worker\@.service` as you did in `/usr/lib/systemd/system/osbuild-composer.service`?

**Comment by mattpielm** [comment]
That did work, thanks for tip! For anyone reading, take the Ansible play above and apply to both /usr/lib/systemd/system/osbuild-composer.service and /usr/lib/systemd/system/osbuild-worker@.service (and systemctl daemon-reload)

**Comment by teg** [comment]
Thanks for confirming @mattpielm (and for suggesting the env vars in the first place).

**Comment by mattpielm** [comment]
Hat tip to @liveaverage on the env vars, he suggested it separately.
