### ISSUE TITLE
Remote worker cannot make directories in /var/cache

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#668]
While working on remote worker deployments, this error occurred on RHEL 8.2:

```
May 24 12:57:20 rhel82-3956 systemd[1]: Started OSBuild Composer Remote Worker (composer:8700).
May 24 12:57:20 rhel82-3956 systemd[7733]: osbuild-remote-worker@composer:8700.service: Failed to set up special execution directory in /var/cache: Permission denied
May 24 12:57:20 rhel82-3956 systemd[7733]: osbuild-remote-worker@composer:8700.service: Failed at step CACHE_DIRECTORY spawning /usr/libexec/osbuild-composer/osbuild-worker: Permission denied
May 24 12:57:20 rhel82-3956 systemd[1]: osbuild-remote-worker@composer:8700.service: Main process exited, code=exited, status=239/CACHE_DIRECTORY
May 24 12:57:20 rhel82-3956 systemd[1]: osbuild-remote-worker@composer:8700.service: Failed with result 'exit-code'.
```

**Comment by major** [comment]
```
May 26 13:23:24 fedora31-4230 systemd[1]: osbuild-remote-worker@composer:8700.service: Main process exited, code=exited, status=1/FAILURE
May 26 13:23:24 fedora31-4230 systemd[1]: osbuild-remote-worker@composer:8700.service: Failed with result 'exit-code'.
May 26 13:23:26 fedora31-4230 osbuild-composer[3323]: Traceback (most recent call last):
May 26 13:23:26 fedora31-4230 osbuild-composer[3323]:   File "dnf-json", line 102, in <module>
May 26 13:23:26 fedora31-4230 osbuild-composer[3323]:     base = create_base(repos, module_platform_id, persistdir, cachedir, arch)
May 26 13:23:26 fedora31-4230 osbuild-composer[3323]:   File "dnf-json", line 59, in create_base
May 26 13:23:26 fedora31-4230 osbuild-composer[3323]:     base.fill_sack(load_system_repo=False)
May 26 13:23:26 fedora31-4230 osbuild-composer[3323]:   File "/usr/lib/python3.7/site-packages/dnf/base.py", line 392, in fill_sack
May 26 13:23:26 fedora31-4230 osbuild-composer[3323]:     self._add_repo_to_sack(r)
May 26 13:23:26 fedora31-4230 osbuild-composer[3323]:   File "/usr/lib/python3.7/site-packages/dnf/base.py", line 144, in _add_repo_to_sack
May 26 13:23:26 fedora31-4230 osbuild-composer[3323]:     self._sack.load_repo(repo._repo, build_cache=True, **mdload_flags)
May 26 13:23:26 fedora31-4230 osbuild-composer[3323]: OSError: cannot create temporary file: /var/cache/osbuild-composer/rpmmd/fedora.solv.tIqm2O
May 26 13:23:26 fedora31-4230 sudo[3376]: pam_unix(sudo:session): session closed for user root
```

**Comment by major** [comment]
@larskarlitski I'll give it a try with this line hacked out: https://github.com/osbuild/osbuild-composer/blob/master/distribution/osbuild-remote-worker%40.service#L9

**Comment by major** [comment]
Removing `CacheDirectory` definitely helps. This is getting removed in #583. Thanks, @teg!
