### ISSUE TITLE
aarch64: No space left on device during compose

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#870]
I was running a test in Beaker on real hardware and composes keep failing on aarch64 running RHEL 8.3.0:

```
cp: error writing '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./boot/initramfs-4.18.0-221.el8.aarch64.img': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./boot/loader': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./boot/grub2': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./boot/dtb-4.18.0-221.el8.aarch64': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./media': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./srv': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./sys': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./mnt': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./tmp': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./proc': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./opt': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./etc': No space left on device
cp: cannot create symbolic link '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./lib64': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./root': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./run': No space left on device
cp: cannot create symbolic link '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./bin': No space left on device
cp: cannot create directory '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./home': No space left on device
cp: cannot create symbolic link '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./lib': No space left on device
cp: cannot create symbolic link '/run/osbuild/output/osbuild-mnt-u0e6m9tf/./sbin': No space left on device
Traceback (most recent call last):
  File "/run/osbuild/lib/assemblers/org.osbuild.qemu", line 690, in <module>
    ret = main(args["tree"], args["output_dir"], args["options"], remoteloop.LoopClient("/run/osbuild/api/remoteloop"))
  File "/run/osbuild/lib/assemblers/org.osbuild.qemu", line 651, in main
    subprocess.run(["cp", "-a", f"{tree}/.", root], check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cp', '-a', '/run/osbuild/tree/.', '/run/osbuild/output/osbuild-mnt-u0e6m9tf']' returned non-zero exit status 1.
```

However, the filesystem size looks reasonable based on the output of osbuild:

```json
{
  "format": "qcow2",
  "filename": "disk.qcow2",
  "size": 2147483648,
  "ptuuid": "8DFDFF87-C96E-EA48-A3A6-9408F1F6B1EF",
  "pttype": "gpt",
  "partitions": [
    {
      "start": 2048,
      "size": 972800,
      "type": "C12A7328-F81F-11D2-BA4B-00A0C93EC93B",
      "filesystem": {
        "type": "vfat",
        "uuid": "46BB-8120",
        "label": "EFI System Partition",
        "mountpoint": "/boot/efi"
      }
    },
    {
      "start": 976896,
      "filesystem": {
        "type": "xfs",
        "uuid": "0bd700f8-090f-4556-b797-b340297ea1bd",
        "mountpoint": "/"
      }
    }
  ]
}
```

The system has plenty of disk space:

```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         48G     0   48G   0% /dev
tmpfs            48G     0   48G   0% /dev/shm
tmpfs            48G   63M   48G   1% /run
tmpfs            48G     0   48G   0% /sys/fs/cgroup
/dev/sda4        70G  7.7G   63G  11% /
/dev/sda2      1014M  165M  850M  17% /boot
/dev/sda1       599M  6.4M  593M   2% /boot/efi
tmpfs           9.6G     0  9.6G   0% /run/user/0
```

Beaker output: http://lab-02.rhts.eng.bos.redhat.com/beaker/logs/tasks/113135+/113135479/taskout.log
Recipe: https://beaker.engineering.redhat.com/recipes/8565221#tasks

**Comment by major** [comment]
Apparently aarch64 needs an image bigger than 2GB. This worked just fine:

```
composer-cli compose start --size 10240 bash qcow2
Compose 90a377f3-0e2e-474c-b900-554c898db41a added to the queue
```

**Comment by major** [comment]
This was fixed in https://github.com/osbuild/osbuild-composer/commit/3daa751095df881ac52de3470ebf89e49def8bb8
